language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
# command to install dependencies
install: "pip install -r dev_requirements.txt codecov"
# command to run tests
script:
  - flake8 .
  - py.test --cov=pytocli tests/
  - python -m doctest README.md
after_success:
  - codecov